-- NMC Intelligence Oracle 23ai / Oracle Free - V1
-- Execute ONCE while connected as NMC_AI in FREEPDB1 (NOT CDB$ROOT).
-- Additive only: no DROP/TRUNCATE; all maritime evidence in this POC is SYNTHETIC.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
SET SERVEROUTPUT ON

CREATE TABLE NMC_SCHEMA_VERSION (
  VERSION_NUMBER NUMBER(4) PRIMARY KEY,
  DESCRIPTION VARCHAR2(200) NOT NULL,
  APPLIED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NMC_VESSEL (
  IMO VARCHAR2(7 CHAR) PRIMARY KEY,
  VESSEL_NAME VARCHAR2(200 CHAR) NOT NULL,
  FLAG VARCHAR2(80 CHAR),
  VESSEL_TYPE VARCHAR2(80 CHAR),
  OPERATOR_NAME VARCHAR2(250 CHAR),
  DATA_NATURE VARCHAR2(40 CHAR) DEFAULT 'SYNTHETIC_POC' NOT NULL,
  CREATED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_NMC_VESSEL_IMO CHECK (REGEXP_LIKE(IMO, '^[0-9]{7}$'))
);

CREATE TABLE NMC_AI_JOB (
  JOB_ID VARCHAR2(80 CHAR) PRIMARY KEY,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  TOTAL_COUNT NUMBER(5) DEFAULT 0 NOT NULL,
  COMPLETED_COUNT NUMBER(5) DEFAULT 0 NOT NULL,
  FAILED_COUNT NUMBER(5) DEFAULT 0 NOT NULL,
  STARTED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  FINISHED_AT TIMESTAMP(3) WITH TIME ZONE,
  CONSTRAINT CK_NMC_JOB_STATUS CHECK (STATUS IN ('RUNNING','COMPLETED','CANCELLED','FAILED'))
);

CREATE TABLE NMC_AI_ASSESSMENT (
  ASSESSMENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  IMO VARCHAR2(7 CHAR) NOT NULL,
  JOB_ID VARCHAR2(80 CHAR),
  RISK_SCORE NUMBER(5,2) NOT NULL,
  RISK_LEVEL VARCHAR2(12 CHAR) NOT NULL,
  OPERATIONAL_PRIORITY VARCHAR2(40 CHAR) NOT NULL,
  CRITICAL_OPEN_FINDING CHAR(1 CHAR) NOT NULL,
  RULESET_VERSION VARCHAR2(80 CHAR) NOT NULL,
  INPUT_HASH VARCHAR2(64 CHAR),
  SOURCE_MODE VARCHAR2(40 CHAR),
  RULESET_JSON CLOB NOT NULL,
  PSC_SUMMARY_JSON CLOB,
  SOURCE_NATURE VARCHAR2(50 CHAR) DEFAULT 'SYNTHETIC_NOT_RIYADH_MOU' NOT NULL,
  ASSESSED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  VERIFIED_BY_AUTHORITY CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  CONSTRAINT FK_NMC_ASMT_VESSEL FOREIGN KEY (IMO) REFERENCES NMC_VESSEL(IMO),
  CONSTRAINT FK_NMC_ASMT_JOB FOREIGN KEY (JOB_ID) REFERENCES NMC_AI_JOB(JOB_ID),
  CONSTRAINT CK_NMC_ASMT_RULESET_JSON CHECK (RULESET_JSON IS JSON),
  CONSTRAINT CK_NMC_ASMT_PSC_JSON CHECK (PSC_SUMMARY_JSON IS JSON),
  CONSTRAINT CK_NMC_ASMT_SCORE CHECK (RISK_SCORE BETWEEN 0 AND 100),
  CONSTRAINT CK_NMC_ASMT_LEVEL CHECK (RISK_LEVEL IN ('Normal','Watch','High','Critical')),
  CONSTRAINT CK_NMC_ASMT_CRITICAL CHECK (CRITICAL_OPEN_FINDING IN ('Y','N')),
  CONSTRAINT CK_NMC_ASMT_VERIFIED CHECK (VERIFIED_BY_AUTHORITY IN ('Y','N'))
);
CREATE INDEX IX_NMC_ASMT_IMO_TIME ON NMC_AI_ASSESSMENT(IMO, ASSESSED_AT DESC);

CREATE TABLE NMC_AI_RISK_FACTOR (
  ASSESSMENT_ID VARCHAR2(36 CHAR) NOT NULL,
  FACTOR_KEY VARCHAR2(30 CHAR) NOT NULL,
  SEVERITY NUMBER(5,2) NOT NULL,
  CONFIDENCE NUMBER(5,4) NOT NULL,
  AGENT_CODE VARCHAR2(6 CHAR) NOT NULL,
  REASON_TEXT VARCHAR2(2000 CHAR),
  EVIDENCE_IDS_JSON CLOB NOT NULL,
  CONSTRAINT PK_NMC_FACTOR PRIMARY KEY (ASSESSMENT_ID, FACTOR_KEY),
  CONSTRAINT FK_NMC_FACTOR_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT CK_NMC_FACTOR_KEY CHECK (FACTOR_KEY IN ('movement','inspection','certificate','dataQuality','history')),
  CONSTRAINT CK_NMC_FACTOR_SEVERITY CHECK (SEVERITY BETWEEN 0 AND 100),
  CONSTRAINT CK_NMC_FACTOR_CONF CHECK (CONFIDENCE BETWEEN 0 AND 1),
  CONSTRAINT CK_NMC_FACTOR_EVIDENCE_JSON CHECK (EVIDENCE_IDS_JSON IS JSON)
);

CREATE TABLE NMC_VESSEL_CURRENT_STATE (
  IMO VARCHAR2(7 CHAR) PRIMARY KEY,
  ASSESSMENT_ID VARCHAR2(36 CHAR),
  STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  LAST_CHECKED_AT TIMESTAMP(3) WITH TIME ZONE,
  NEXT_CHECK_AT TIMESTAMP(3) WITH TIME ZONE,
  ATTEMPTED_AT TIMESTAMP(3) WITH TIME ZONE,
  REFRESH_FAILURE VARCHAR2(100 CHAR),
  FAILURE_REASON VARCHAR2(100 CHAR),
  UPDATED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_STATE_VESSEL FOREIGN KEY (IMO) REFERENCES NMC_VESSEL(IMO),
  CONSTRAINT FK_NMC_STATE_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT CK_NMC_STATE_STATUS CHECK (STATUS IN ('PENDING','COMPLETED','FAILED'))
);
CREATE INDEX IX_NMC_STATE_DUE ON NMC_VESSEL_CURRENT_STATE(STATUS, NEXT_CHECK_AT);

CREATE TABLE NMC_AI_EXECUTION (
  EXECUTION_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  ASSESSMENT_ID VARCHAR2(36 CHAR) NOT NULL,
  AGENT_CODE VARCHAR2(6 CHAR) NOT NULL,
  EXECUTION_STATUS VARCHAR2(30 CHAR) NOT NULL,
  STARTED_AT TIMESTAMP(3) WITH TIME ZONE,
  FINISHED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_EXEC_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID)
);

CREATE TABLE NMC_DATA_SOURCE (
  SOURCE_ID VARCHAR2(60 CHAR) PRIMARY KEY,
  SOURCE_NAME VARCHAR2(200 CHAR) NOT NULL,
  SOURCE_CLASS VARCHAR2(40 CHAR) NOT NULL,
  AUTHORITY_VERIFIED CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  SOURCE_NATURE VARCHAR2(50 CHAR) DEFAULT 'SYNTHETIC_POC' NOT NULL,
  LAST_SYNC_AT TIMESTAMP(3) WITH TIME ZONE,
  CONSTRAINT CK_NMC_SOURCE_VERIFIED CHECK (AUTHORITY_VERIFIED IN ('Y','N'))
);

CREATE TABLE NMC_EVIDENCE (
  ASSESSMENT_ID VARCHAR2(36 CHAR) NOT NULL,
  EVIDENCE_ID VARCHAR2(160 CHAR) NOT NULL,
  SOURCE_ID VARCHAR2(60 CHAR),
  VERIFIED_BY_AUTHORITY CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_NMC_EVIDENCE PRIMARY KEY (ASSESSMENT_ID, EVIDENCE_ID),
  CONSTRAINT FK_NMC_EVID_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT FK_NMC_EVID_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES NMC_DATA_SOURCE(SOURCE_ID)
);

CREATE TABLE NMC_AI_FINDING (
  FINDING_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  ASSESSMENT_ID VARCHAR2(36 CHAR) NOT NULL,
  FINDING_TYPE VARCHAR2(40 CHAR) NOT NULL,
  SUMMARY_TEXT VARCHAR2(2000 CHAR) NOT NULL,
  SEVERITY NUMBER(5,2),
  CONFIDENCE NUMBER(5,4),
  EVIDENCE_IDS_JSON CLOB NOT NULL,
  REQUIRES_HUMAN_REVIEW CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CONSTRAINT FK_NMC_FIND_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT CK_NMC_FIND_EVID_JSON CHECK (EVIDENCE_IDS_JSON IS JSON)
);

CREATE TABLE NMC_DATA_QUALITY (
  ASSESSMENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  QUALITY_SCORE NUMBER(5,2),
  CALCULATION_VERSION VARCHAR2(80 CHAR),
  BREAKDOWN_JSON CLOB,
  CALCULATION_STATUS VARCHAR2(30 CHAR) DEFAULT 'NOT_CALCULATED' NOT NULL,
  CONSTRAINT FK_NMC_DQ_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT CK_NMC_DQ_SCORE CHECK (QUALITY_SCORE IS NULL OR QUALITY_SCORE BETWEEN 0 AND 100),
  CONSTRAINT CK_NMC_DQ_JSON CHECK (BREAKDOWN_JSON IS JSON),
  CONSTRAINT CK_NMC_DQ_STATUS CHECK (CALCULATION_STATUS IN ('NOT_CALCULATED','CALCULATED','INSUFFICIENT_EVIDENCE'))
);

CREATE TABLE NMC_DATA_CONFLICT (
  CONFLICT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  IMO VARCHAR2(7 CHAR) NOT NULL,
  FIRST_DETECTED_ASSESSMENT_ID VARCHAR2(36 CHAR),
  LAST_ASSESSMENT_ID VARCHAR2(36 CHAR),
  SOURCE_A_EVIDENCE_ID VARCHAR2(160 CHAR),
  SOURCE_B_EVIDENCE_ID VARCHAR2(160 CHAR),
  FIELD_NAME VARCHAR2(100 CHAR),
  CONFLICT_SUMMARY VARCHAR2(2000 CHAR),
  STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING_REVIEW' NOT NULL,
  HUMAN_DECISION VARCHAR2(2000 CHAR),
  HUMAN_REVIEWED_AT TIMESTAMP(3) WITH TIME ZONE,
  CREATED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_CONFLICT_VESSEL FOREIGN KEY (IMO) REFERENCES NMC_VESSEL(IMO),
  CONSTRAINT FK_NMC_CONFLICT_FIRST FOREIGN KEY (FIRST_DETECTED_ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT FK_NMC_CONFLICT_LAST FOREIGN KEY (LAST_ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID),
  CONSTRAINT CK_NMC_CONFLICT_STATUS CHECK (STATUS IN ('PENDING_REVIEW','CONFIRMED','DISMISSED','RESOLVED'))
);

CREATE TABLE NMC_INTELLIGENCE_EVENT (
  EVENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  IMO VARCHAR2(7 CHAR) NOT NULL,
  ASSESSMENT_ID VARCHAR2(36 CHAR),
  EVENT_TYPE VARCHAR2(60 CHAR) NOT NULL,
  EVENT_DESCRIPTION VARCHAR2(2000 CHAR),
  PREVIOUS_RISK_SCORE NUMBER(5,2),
  NEW_RISK_SCORE NUMBER(5,2),
  OCCURRED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DETECTED_AT TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  SOURCE_NATURE VARCHAR2(50 CHAR) DEFAULT 'SYNTHETIC_POC' NOT NULL,
  CONSTRAINT FK_NMC_EVENT_VESSEL FOREIGN KEY (IMO) REFERENCES NMC_VESSEL(IMO),
  CONSTRAINT FK_NMC_EVENT_ASMT FOREIGN KEY (ASSESSMENT_ID) REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID)
);
CREATE INDEX IX_NMC_EVENT_VESSEL_TIME ON NMC_INTELLIGENCE_EVENT(IMO, OCCURRED_AT DESC);

INSERT INTO NMC_SCHEMA_VERSION(VERSION_NUMBER,DESCRIPTION)
VALUES(1,'NMC Intelligence V1 / Oracle Free - append-only risk assessments and current state');
COMMIT;
PROMPT NMC_AI schema V1 created. No data was deleted.
