-- Run as NMC_AI against FREEPDB1, read-only post-migration checks.
SET PAGESIZE 60
SET LINESIZE 160
SELECT SYS_CONTEXT('USERENV','CON_NAME') AS pdb,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS current_schema FROM DUAL;
SELECT VERSION_NUMBER,DESCRIPTION,APPLIED_AT FROM NMC_SCHEMA_VERSION;
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'NMC_%' ORDER BY TABLE_NAME;
SELECT COUNT(*) AS vessel_count FROM NMC_VESSEL;
SELECT COUNT(*) AS assessment_count FROM NMC_AI_ASSESSMENT;
SELECT COUNT(*) AS current_states FROM NMC_VESSEL_CURRENT_STATE;
SELECT COUNT(*) AS factor_count FROM NMC_AI_RISK_FACTOR;
SELECT COUNT(*) AS risk_history_events FROM NMC_INTELLIGENCE_EVENT;
