-- NMC Dashboard Workspace V2: additive, non-destructive migration.
-- Execute AS the existing NMC_AI schema owner after reviewing backup/rollback plan.
-- This migration DOES NOT modify or recalculate any existing vessel/AI/Risk data.
-- Run once; if already present, verify objects before continuing.

CREATE TABLE NMC_DASHBOARD (
  DASHBOARD_ID     VARCHAR2(100 CHAR) PRIMARY KEY,
  TITLE            VARCHAR2(100 CHAR) NOT NULL,
  STATUS           VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL
                   CONSTRAINT CK_NMC_DASHBOARD_STATUS CHECK (STATUS IN ('DRAFT','PUBLISHED','ARCHIVED')),
  VERSION_NO       NUMBER(10,0) DEFAULT 1 NOT NULL
                   CONSTRAINT CK_NMC_DASHBOARD_VERSION CHECK (VERSION_NO >= 1),
  DOC_JSON         CLOB NOT NULL CONSTRAINT CK_NMC_DASHBOARD_JSON CHECK (DOC_JSON IS JSON),
  CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_ROLE     VARCHAR2(24 CHAR) NOT NULL
);
CREATE INDEX IX_NMC_DASHBOARD_STATUS ON NMC_DASHBOARD(STATUS, UPDATED_AT);

CREATE TABLE NMC_DASHBOARD_REVISION (
  DASHBOARD_ID     VARCHAR2(100 CHAR) NOT NULL,
  VERSION_NO       NUMBER(10,0) NOT NULL,
  ACTION_NAME      VARCHAR2(16 CHAR) NOT NULL
                   CONSTRAINT CK_NMC_DB_REV_ACTION CHECK (ACTION_NAME IN ('CREATED','UPDATED','PUBLISHED','ARCHIVED')),
  ACTOR_ROLE       VARCHAR2(24 CHAR) NOT NULL,
  DOC_JSON         CLOB NOT NULL CONSTRAINT CK_NMC_DB_REV_JSON CHECK (DOC_JSON IS JSON),
  CHANGED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMC_DASHBOARD_REVISION PRIMARY KEY (DASHBOARD_ID,VERSION_NO),
  CONSTRAINT FK_NMC_DASHBOARD_REVISION FOREIGN KEY (DASHBOARD_ID)
    REFERENCES NMC_DASHBOARD(DASHBOARD_ID)
);

COMMIT;

-- Verification (read only):
-- SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('NMC_DASHBOARD','NMC_DASHBOARD_REVISION');
-- SELECT COUNT(*) FROM NMC_DASHBOARD;
-- SELECT COUNT(*) FROM NMC_DASHBOARD_REVISION;
-- No grant changes or other NMC schema migrations are required.
