-- Migration 003: National Maritime Center operational alerts (POC)
-- ADDITIVE / NON-DESTRUCTIVE. Run once AS NMC_AI in FREEPDB1 after backup.
-- No changes to AI assessments, stored risk, risk rules, dashboard data,
-- existing business cases, existing schema, or Oracle container volumes.
--
-- Check existence first:
-- SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('NMC_ALERT','NMC_ALERT_AUDIT');
-- Both names must be absent before running this file.

CREATE TABLE NMC_ALERT (
  ALERT_ID        VARCHAR2(36 CHAR) PRIMARY KEY,
  ALERT_KEY       VARCHAR2(85 CHAR) NOT NULL,
  IMO             VARCHAR2(7 CHAR) NOT NULL,
  STATUS          VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
  SEVERITY        VARCHAR2(12 CHAR) NOT NULL,
  ASSIGNED_ROLE   VARCHAR2(24 CHAR) NOT NULL,
  VERSION_NO      NUMBER(10,0) DEFAULT 1 NOT NULL,
  DOC_JSON        CLOB NOT NULL CONSTRAINT CK_NMC_ALERT_JSON CHECK (DOC_JSON IS JSON),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_NMC_ALERT_KEY UNIQUE (ALERT_KEY),
  CONSTRAINT CK_NMC_ALERT_IMO CHECK (REGEXP_LIKE(IMO, '^[0-9]{7}$')),
  CONSTRAINT CK_NMC_ALERT_STATUS CHECK (
    STATUS IN ('OPEN','ACKNOWLEDGED','IN_PROGRESS','ESCALATED','RESOLVED')),
  CONSTRAINT CK_NMC_ALERT_SEVERITY CHECK (SEVERITY IN ('HIGH','CRITICAL')),
  CONSTRAINT CK_NMC_ALERT_ROLE CHECK (
    ASSIGNED_ROLE IN ('NMC_OFFICER','NMC_SUPERVISOR')),
  CONSTRAINT CK_NMC_ALERT_VERSION CHECK (VERSION_NO >= 1)
);

CREATE INDEX IX_NMC_ALERT_STATUS ON NMC_ALERT(STATUS,SEVERITY,CREATED_AT);
CREATE INDEX IX_NMC_ALERT_IMO ON NMC_ALERT(IMO);

CREATE TABLE NMC_ALERT_AUDIT (
  ALERT_ID       VARCHAR2(36 CHAR) NOT NULL,
  VERSION_NO     NUMBER(10,0) NOT NULL,
  ACTION_NAME    VARCHAR2(24 CHAR) NOT NULL,
  ACTOR_ROLE     VARCHAR2(24 CHAR) NOT NULL,
  NOTE           VARCHAR2(500 CHAR),
  CHANGED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMC_ALERT_AUDIT PRIMARY KEY (ALERT_ID,VERSION_NO),
  CONSTRAINT FK_NMC_ALERT_AUDIT FOREIGN KEY(ALERT_ID) REFERENCES NMC_ALERT(ALERT_ID),
  CONSTRAINT CK_NMC_ALERT_AUDIT_ACTION CHECK (
    ACTION_NAME IN ('DETECTED','ACKNOWLEDGE','START_FOLLOW_UP','ESCALATE','RESOLVE'))
);
COMMIT;

-- Verification:
-- SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('NMC_ALERT','NMC_ALERT_AUDIT');
-- SELECT COUNT(*) FROM NMC_ALERT;
-- SELECT COUNT(*) FROM NMC_ALERT_AUDIT;
-- Do NOT rerun partially completed DDL. Review it before any recovery.
