-- Migration 004: National Maritime Center operational cases and decision audit
-- Manual, additive, non-destructive. RUN ONCE as NMC_AI in FREEPDB1 after backup.
-- Check both tables are ABSENT before executing:
-- SELECT TABLE_NAME FROM USER_TABLES
-- WHERE TABLE_NAME IN ('NMC_CASE','NMC_CASE_AUDIT');
-- Does NOT update existing maritime, AI, risk, dashboard or alert records.

CREATE TABLE NMC_CASE (
  CASE_ID           VARCHAR2(36 CHAR) PRIMARY KEY,
  IMO               VARCHAR2(7 CHAR) NOT NULL,
  SOURCE_ALERT_ID   VARCHAR2(36 CHAR) NOT NULL,
  ACTIVE_IMO        VARCHAR2(7 CHAR),
  STATUS            VARCHAR2(24 CHAR) DEFAULT 'OPEN' NOT NULL,
  VERSION_NO        NUMBER(10,0) NOT NULL,
  DOC_JSON          CLOB NOT NULL CONSTRAINT CK_NMC_CASE_JSON CHECK (DOC_JSON IS JSON),
  CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_ROLE      VARCHAR2(24 CHAR) NOT NULL,
  CONSTRAINT UQ_NMC_CASE_ACTIVE_IMO UNIQUE (ACTIVE_IMO),
  CONSTRAINT UQ_NMC_CASE_ALERT UNIQUE (SOURCE_ALERT_ID),
  CONSTRAINT FK_NMC_CASE_ALERT FOREIGN KEY (SOURCE_ALERT_ID)
    REFERENCES NMC_ALERT(ALERT_ID),
  CONSTRAINT CK_NMC_CASE_IMO CHECK (REGEXP_LIKE(IMO, '^[0-9]{7}$')),
  CONSTRAINT CK_NMC_CASE_STATUS CHECK (
    STATUS IN ('OPEN','IN_PROGRESS','PENDING_VERIFICATION','RESOLVED')),
  CONSTRAINT CK_NMC_CASE_VERSION CHECK (VERSION_NO >= 1)
);

CREATE INDEX IX_NMC_CASE_STATUS ON NMC_CASE(STATUS,UPDATED_AT);
CREATE INDEX IX_NMC_CASE_IMO ON NMC_CASE(IMO);

CREATE TABLE NMC_CASE_AUDIT (
  CASE_ID          VARCHAR2(36 CHAR) NOT NULL,
  VERSION_NO       NUMBER(10,0) NOT NULL,
  ACTION_NAME      VARCHAR2(32 CHAR) NOT NULL,
  ACTOR_ROLE       VARCHAR2(24 CHAR) NOT NULL,
  NOTE             VARCHAR2(500 CHAR),
  DETAIL_JSON      CLOB NOT NULL CONSTRAINT CK_NMC_CASE_AUDIT_JSON CHECK (DETAIL_JSON IS JSON),
  CHANGED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMC_CASE_AUDIT PRIMARY KEY(CASE_ID,VERSION_NO),
  CONSTRAINT FK_NMC_CASE_AUDIT FOREIGN KEY(CASE_ID) REFERENCES NMC_CASE(CASE_ID),
  CONSTRAINT CK_NMC_CASE_AUDIT_ACTION CHECK (
    ACTION_NAME IN (
      'CREATED','ALERT_LINKED','TASK_START','TASK_COMPLETE','TASK_ESCALATE',
      'DECISION_RECORDED','INSPECTION_RECORDED','RESOLVED'))
);

COMMIT;

-- Read-only post-migration verification:
-- SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('NMC_CASE','NMC_CASE_AUDIT');
-- SELECT COUNT(*) FROM NMC_CASE;
-- SELECT COUNT(*) FROM NMC_CASE_AUDIT;
-- Never rerun this file after a partial Oracle DDL execution.
