-- NMC POC migration 006: versioned operational guidance policy and immutable evaluations.
-- Must be applied once by NMC_AI to existing FREEPDB1 AFTER DBA backup/review.
-- Requires NMC schema v1; no existing assessment/case/risk row is touched.
-- Check USER_TABLES for these names BEFORE running. Do not rerun blindly.
CREATE TABLE NMC_GUIDANCE_POLICY (
  RULE_ID VARCHAR2(80) PRIMARY KEY,
  REVISION NUMBER(9) NOT NULL,
  STATUS VARCHAR2(12) NOT NULL CHECK (STATUS IN ('ACTIVE','DRAFT','INACTIVE')),
  RULE_JSON CLOB NOT NULL CHECK (RULE_JSON IS JSON),
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE NMC_GUIDANCE_POLICY_AUDIT (
  AUDIT_ID VARCHAR2(36) PRIMARY KEY,
  RULE_ID VARCHAR2(80) NOT NULL,
  REVISION NUMBER(9) NOT NULL,
  ACTION_NAME VARCHAR2(20) NOT NULL CHECK (ACTION_NAME IN ('SEED','CREATE','EDIT','PUBLISH','DISABLE')),
  ACTOR_ROLE VARCHAR2(20) NOT NULL,
  RULE_JSON CLOB NOT NULL CHECK (RULE_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_NMC_GUIDANCE_AUDIT ON NMC_GUIDANCE_POLICY_AUDIT(RULE_ID,REVISION);
CREATE TABLE NMC_GUIDANCE_RESULT (
  ASSESSMENT_ID VARCHAR2(36) NOT NULL,
  RULE_ID VARCHAR2(80) NOT NULL,
  RULE_REVISION NUMBER(9) NOT NULL,
  RESULT_JSON CLOB NOT NULL CHECK (RESULT_JSON IS JSON),
  GENERATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMC_GUIDANCE_RESULT PRIMARY KEY (ASSESSMENT_ID,RULE_ID,RULE_REVISION),
  CONSTRAINT FK_NMC_GUIDANCE_ASSESSMENT FOREIGN KEY(ASSESSMENT_ID)
    REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID)
);
-- After migration, restart ONLY ai-proxy when deploying the feature.
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'NMC_GUIDANCE_%' ORDER BY TABLE_NAME;
