-- NMC POC migration 007: immutable central risk-policy history, one active pointer,
-- and per-assessment historical score projections. NO existing tables are modified.
-- Run ONCE as NMC_AI in FREEPDB1 after Oracle backup and schema verification.
-- Before execution: SELECT table_name FROM user_tables WHERE table_name LIKE 'NMC_RISK_POLICY%';
-- ALL objects below must be absent; stop if partially present. Oracle DDL auto-commits.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE NMC_RISK_POLICY_VERSION (
  VERSION_NO NUMBER(9) PRIMARY KEY,
  POLICY_REF VARCHAR2(80) NOT NULL UNIQUE,
  PREVIOUS_VERSION_NO NUMBER(9),
  CONFIG_JSON CLOB NOT NULL CHECK (CONFIG_JSON IS JSON),
  CHANGE_REASON VARCHAR2(500) NOT NULL,
  PUBLISHED_BY VARCHAR2(120) NOT NULL,
  ACTOR_ROLE VARCHAR2(30) NOT NULL,
  PUBLISHED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_RISK_PREVIOUS FOREIGN KEY(PREVIOUS_VERSION_NO)
    REFERENCES NMC_RISK_POLICY_VERSION(VERSION_NO)
);
CREATE TABLE NMC_RISK_POLICY_ACTIVE (
  SINGLETON_ID NUMBER(1) DEFAULT 1 PRIMARY KEY CHECK(SINGLETON_ID=1),
  VERSION_NO NUMBER(9) NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_RISK_ACTIVE FOREIGN KEY(VERSION_NO)
    REFERENCES NMC_RISK_POLICY_VERSION(VERSION_NO)
);
CREATE TABLE NMC_RISK_POLICY_PROJECTION (
  POLICY_VERSION_NO NUMBER(9) NOT NULL,
  ASSESSMENT_ID VARCHAR2(36) NOT NULL,
  IMO VARCHAR2(7) NOT NULL,
  RISK_SCORE NUMBER(3) NOT NULL CHECK(RISK_SCORE BETWEEN 0 AND 100),
  RISK_LEVEL VARCHAR2(12) NOT NULL
    CHECK(RISK_LEVEL IN ('Normal','Watch','High','Critical')),
  OPERATIONAL_PRIORITY VARCHAR2(30) NOT NULL,
  CRITICAL_OPEN_FINDING CHAR(1) NOT NULL CHECK(CRITICAL_OPEN_FINDING IN ('Y','N')),
  CALCULATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMC_RISK_POLICY_PROJECTION PRIMARY KEY(POLICY_VERSION_NO,ASSESSMENT_ID),
  CONSTRAINT FK_NMC_RISK_PROJ_VERSION FOREIGN KEY(POLICY_VERSION_NO)
    REFERENCES NMC_RISK_POLICY_VERSION(VERSION_NO),
  CONSTRAINT FK_NMC_RISK_PROJ_ASSESSMENT FOREIGN KEY(ASSESSMENT_ID)
    REFERENCES NMC_AI_ASSESSMENT(ASSESSMENT_ID)
);
CREATE INDEX IDX_NMC_RISK_PROJ_IMO ON NMC_RISK_POLICY_PROJECTION(IMO,POLICY_VERSION_NO);
-- The application seeds version 1 only after verifying all three tables exist.
-- Never insert a guessed version derived from an individual browser localStorage.
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'NMC_RISK_POLICY%' ORDER BY TABLE_NAME;
