-- NMC risk enhancements. Apply AFTER migration 007, following backup/verification.
-- Oracle DDL auto-commits; run during a controlled deployment and verify object presence first.
-- Historical rows before this migration legitimately have no factor snapshot.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE NMC_RISK_POLICY_DRAFT (
  DRAFT_ID NUMBER(1) DEFAULT 1 PRIMARY KEY CHECK (DRAFT_ID=1),
  BASE_VERSION_NO NUMBER(9) NOT NULL,
  DRAFT_REVISION NUMBER(9) NOT NULL,
  CONFIG_JSON CLOB NOT NULL CHECK (CONFIG_JSON IS JSON),
  UPDATED_BY VARCHAR2(120) NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_RISK_DRAFT_BASE FOREIGN KEY (BASE_VERSION_NO)
    REFERENCES NMC_RISK_POLICY_VERSION(VERSION_NO)
);
ALTER TABLE NMC_RISK_POLICY_PROJECTION ADD (
  FACTOR_SNAPSHOT_JSON CLOB CHECK (FACTOR_SNAPSHOT_JSON IS JSON)
);
-- Verify:
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME='NMC_RISK_POLICY_DRAFT';
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME='NMC_RISK_POLICY_PROJECTION' AND COLUMN_NAME='FACTOR_SNAPSHOT_JSON';
