-- Migration 009 / Smart Inspection STEP 00-04 / ADDITIVE ONLY.
-- Run as NMC_AI in FREEPDB1 AFTER 008, following a verified Oracle backup.
-- Run ONCE. Oracle DDL autocommits; stop if any of these objects already exist.
-- Stores SI-only event provenance, human decisions, new SI inspection case shells,
-- and immutable priority rules. Does NOT alter NMC_AI_ASSESSMENT, risk or cases.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE SI_CANDIDATE_EVENT (
  EVENT_KEY VARCHAR2(64) PRIMARY KEY,
  IMO VARCHAR2(7) NOT NULL,
  SOURCE_TYPE VARCHAR2(24) NOT NULL
    CHECK (SOURCE_TYPE IN ('SERVICE_REQUEST','PSC_PORT_CALL')),
  REGIME VARCHAR2(32) NOT NULL,
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_SI_EVENT_IMO ON SI_CANDIDATE_EVENT (IMO);
CREATE TABLE SI_CANDIDATE_DECISION (
  DECISION_ID VARCHAR2(36) PRIMARY KEY,
  CANDIDATE_KEY VARCHAR2(100) NOT NULL,
  IMO VARCHAR2(7) NOT NULL,
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_SI_DECISION_IMO ON SI_CANDIDATE_DECISION (IMO);
CREATE TABLE SI_INSPECTION_CASE (
  CASE_ID VARCHAR2(36) PRIMARY KEY,
  CANDIDATE_KEY VARCHAR2(100) NOT NULL UNIQUE,
  IMO VARCHAR2(7) NOT NULL,
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_SI_CASE_IMO ON SI_INSPECTION_CASE (IMO);
CREATE TABLE SI_TARGETING_RULE_VERSION (
  VERSION_NO NUMBER(9) PRIMARY KEY,
  CONFIG_JSON CLOB NOT NULL CHECK (CONFIG_JSON IS JSON),
  PUBLISHED_BY VARCHAR2(120) NOT NULL,
  REASON VARCHAR2(500) NOT NULL,
  PUBLISHED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
-- The server seeds VERSION_NO=1 only AFTER all four tables are verified.
-- Post-checks (read only):
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'SI_%' ORDER BY TABLE_NAME;
SELECT COUNT(*) AS ORIGINAL_ASSESSMENTS FROM NMC_AI_ASSESSMENT;
SELECT COUNT(*) AS ORIGINAL_RISK_PROJECTIONS FROM NMC_RISK_POLICY_PROJECTION;
