-- SMART INSPECTION - additive migration 010 / Preparation + A04 Dossier
-- Apply once AFTER 009, NMC_AI / FREEPDB1, with a verified recoverable Oracle DB backup.
-- Oracle DDL auto-commits. Never rerun if one of these objects is already present.
-- Does not alter NMC assessments, NMC risk, NMC cases, or existing SI decisions.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE SI_PREPARATION_DOSSIER (
  CASE_ID VARCHAR2(36) PRIMARY KEY,
  VERSION_NO NUMBER(9) NOT NULL,
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SI_PREP_CASE FOREIGN KEY (CASE_ID)
    REFERENCES SI_INSPECTION_CASE(CASE_ID)
);
CREATE TABLE SI_PREPARATION_AUDIT (
  AUDIT_ID VARCHAR2(36) PRIMARY KEY,
  CASE_ID VARCHAR2(36) NOT NULL,
  VERSION_NO NUMBER(9) NOT NULL,
  ACTION_NAME VARCHAR2(40) NOT NULL,
  ACTOR VARCHAR2(120) NOT NULL,
  REASON VARCHAR2(500),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SI_PREP_AUDIT_CASE FOREIGN KEY (CASE_ID)
    REFERENCES SI_INSPECTION_CASE(CASE_ID)
);
CREATE INDEX IDX_SI_PREP_AUDIT_CASE ON SI_PREPARATION_AUDIT (CASE_ID,VERSION_NO);

-- Read-only verification / expected two tables, one index:
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN
  ('SI_PREPARATION_DOSSIER','SI_PREPARATION_AUDIT') ORDER BY TABLE_NAME;
SELECT COUNT(*) AS NMC_SOURCE_AI_ASSESSMENTS FROM NMC_AI_ASSESSMENT;
SELECT COUNT(*) AS NMC_SOURCE_RISK_PROJECTIONS FROM NMC_RISK_POLICY_PROJECTION;
