-- Smart Inspection SI-P01 - additive migration 011 (after 009; 010 may coexist).
-- Apply ONCE under NMC_AI / FREEPDB1 after a verified, restorable Oracle backup.
-- Persists immutable, evidence-linked AI ranking runs separate from all NMC
-- assessment, official risk, inspection decisions and source events.
-- Oracle DDL auto-commits; do not repeat if partly applied.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE SI_AI_PRIORITY_RUN (
  RUN_ID VARCHAR2(36) PRIMARY KEY,
  POLICY_VERSION NUMBER(9) NOT NULL,
  RISK_POLICY_REVISION NUMBER(9) NOT NULL,
  SNAPSHOT_HASH VARCHAR2(64) NOT NULL,
  RUN_STATUS VARCHAR2(16) NOT NULL
    CHECK (RUN_STATUS IN ('SUCCEEDED','FAILED')),
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_SI_P01_PRIORITY_HISTORY
  ON SI_AI_PRIORITY_RUN (CREATED_AT, POLICY_VERSION);
SELECT TABLE_NAME FROM USER_TABLES
 WHERE TABLE_NAME = 'SI_AI_PRIORITY_RUN';
SELECT COUNT(*) AS INITIAL_SI_PRIORITY_RUNS FROM SI_AI_PRIORITY_RUN;
SELECT COUNT(*) AS UNCHANGED_NMC_AI_ASSESSMENTS FROM NMC_AI_ASSESSMENT;
SELECT COUNT(*) AS UNCHANGED_NMC_RISK_PROJECTIONS FROM NMC_RISK_POLICY_PROJECTION;
