-- 012: PSC targeting selection and quota configuration. AFTER 009 & 011.
-- ADDITIVE ONLY, Oracle DDL auto-commits. Verify backup and schema first.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE SI_PSC_SELECTION_POLICY (
  VERSION_NO NUMBER(9) PRIMARY KEY,
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE SI_PSC_SELECTION_DECISION (
  DECISION_ID VARCHAR2(36) PRIMARY KEY,
  EVENT_KEY VARCHAR2(64) NOT NULL,
  IMO VARCHAR2(7) NOT NULL,
  ACTION VARCHAR2(16) NOT NULL CHECK (ACTION IN ('SELECT','NOT_SELECT')),
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_SI_PSC_SELECT_EVENT ON SI_PSC_SELECTION_DECISION (EVENT_KEY, CREATED_AT);
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN
  ('SI_PSC_SELECTION_POLICY','SI_PSC_SELECTION_DECISION');
SELECT COUNT(*) AS SELECTION_DECISIONS FROM SI_PSC_SELECTION_DECISION;
