-- SI POC V1: case-specific inspection execution, reports, CAPA, follow-up and closure.
-- Apply ONCE manually AFTER migration 009, 010, 011, 012, recoverable backup verified.
-- DDL auto-commits. DO NOT rerun; verify absence before applying.
-- Does NOT modify NMC risk, current case records, official PSC, or Airia results.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE SI_INSPECTION_LIFECYCLE (
  CASE_ID VARCHAR2(36) PRIMARY KEY,
  VERSION_NO NUMBER(9) NOT NULL,
  DOC_JSON CLOB NOT NULL CHECK (DOC_JSON IS JSON),
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SI_LIFECYCLE_CASE FOREIGN KEY (CASE_ID)
    REFERENCES SI_INSPECTION_CASE(CASE_ID)
);
CREATE TABLE SI_INSPECTION_LIFECYCLE_AUDIT (
  AUDIT_ID VARCHAR2(36) PRIMARY KEY,
  CASE_ID VARCHAR2(36) NOT NULL,
  VERSION_NO NUMBER(9) NOT NULL,
  ACTION_NAME VARCHAR2(50) NOT NULL,
  ACTOR VARCHAR2(120) NOT NULL,
  REASON VARCHAR2(500),
  STATE_JSON CLOB NOT NULL CHECK (STATE_JSON IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SI_LIFECYCLE_AUDIT FOREIGN KEY (CASE_ID)
    REFERENCES SI_INSPECTION_CASE(CASE_ID)
);
CREATE INDEX IDX_SI_LIFECYCLE_AUDIT
  ON SI_INSPECTION_LIFECYCLE_AUDIT (CASE_ID,VERSION_NO);
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN
 ('SI_INSPECTION_LIFECYCLE','SI_INSPECTION_LIFECYCLE_AUDIT') ORDER BY TABLE_NAME;
