-- NMC A03 Google Drive document intelligence POC, additive schema migration 015.
-- Apply ONCE, after verified backup and migration 014 (which follows 003/013).
-- Uses existing NMC_AI Oracle schema; this does not touch legacy risk/case tables.
-- Oracle DDL auto-commits: stop and inspect on partial failure; do not rerun blindly.
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE NMC_VESSEL_DOCUMENT (
  DOC_KEY       VARCHAR2(160 CHAR) PRIMARY KEY,
  DOCUMENT_ID   VARCHAR2(36 CHAR) NOT NULL,
  IMO           VARCHAR2(7 CHAR) NOT NULL,
  FILE_ID       VARCHAR2(130 CHAR) NOT NULL,
  VERSION_NO    NUMBER(10,0) NOT NULL,
  DOC_JSON      CLOB NOT NULL CONSTRAINT CK_NMC_DOC_JSON CHECK (DOC_JSON IS JSON),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_NMC_DOC_IMO CHECK (REGEXP_LIKE(IMO,'^[0-9]{7}$')),
  CONSTRAINT CK_NMC_DOC_VERSION CHECK (VERSION_NO >= 1)
);
CREATE INDEX IX_NMC_VESSEL_DOCUMENT_IMO ON NMC_VESSEL_DOCUMENT (IMO);
CREATE TABLE NMC_VESSEL_DOCUMENT_AUDIT (
  AUDIT_ID      VARCHAR2(36 CHAR) PRIMARY KEY,
  DOCUMENT_ID   VARCHAR2(36 CHAR) NOT NULL,
  DOC_KEY       VARCHAR2(160 CHAR) NOT NULL,
  VERSION_NO    NUMBER(10,0) NOT NULL,
  ACTION_NAME   VARCHAR2(40 CHAR) NOT NULL,
  ACTOR         VARCHAR2(100 CHAR) NOT NULL,
  STATE_JSON    CLOB NOT NULL CONSTRAINT CK_NMC_DOC_AUDIT_JSON CHECK (STATE_JSON IS JSON),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_NMC_DOC_AUDIT FOREIGN KEY(DOC_KEY) REFERENCES NMC_VESSEL_DOCUMENT(DOC_KEY),
  CONSTRAINT UQ_NMC_DOC_AUDIT_VERSION UNIQUE(DOC_KEY,VERSION_NO)
);
CREATE INDEX IX_NMC_DOC_AUDIT_DOC ON NMC_VESSEL_DOCUMENT_AUDIT(DOC_KEY,CREATED_AT);
SELECT TABLE_NAME FROM USER_TABLES
 WHERE TABLE_NAME IN ('NMC_VESSEL_DOCUMENT','NMC_VESSEL_DOCUMENT_AUDIT')
 ORDER BY TABLE_NAME;
